// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AD_Manager.Models;

public partial class user_admin
{
    public int ID { get; set; }

    public string user_name { get; set; }

    public string user_password { get; set; }
}